blueprint:
  name: "Aqara Smoke Detector Keep-alive"
  source_url: https://github.com/dagobert/homeassistant-blueprints/blob/stable/automations/aqara-smoke-detector-keepalive/aqara-smoke-detector-keepalive.yaml
  author: "CV"
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  description: |
    # Aqara Smoke Detector Keep-alive

    This automation toggles the heartbeat indicator switch of the Aqara smoke detectors to force them to keep-alive for a faster reaction to software self-tests, alarm and mute commands.

    Use a time pattern trigger to enable the automation. Start with a high value such as <code>/6</code> (every 6 hours). Lower this value if you experience a slow reation time to commands.

    **🔺 The shorter the distance between executing this automation the faster the battery drains. 🔺**

    ---  

    **Version:** 2025-02-19
    **Source Code:** [github.com](https://github.com/dagobert/homeassistant-blueprints/tree/stable/automations/aqara-smoke-detector-keepalive) | **Tickets:** [Issues](https://github.com/dagobert/homeassistant-blueprints/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22Aqara%20smoke%20detector%22)

    For anyone who wants to get updated on changes subscribe to this [GitHub Issue](https://github.com/dagobert/homeassistant-blueprints/issues/4) since as of now Home Assistant has no update facitities for blueprints.

  input:

    smoke_detector_devices:
      name: Smoke detectors
      description: The smoke detectors you want to wake-up reqularly
      selector:
        # TODO: optimize the filter or entity option to be more fault tolerant to
        #       variations of model names
        device:
          filter:
            - manufacturer: Aqara
              model: Smart smoke detector
            - manufacturer: Aqara
              model: Smart smoke detector (JY-GZ-01AQ)
            - manufacturer: Aqara
              model: (JY-GZ-01AQ)
            - manufacturer: Aqara
              model: JY-GZ-01AQ
          multiple: true
    trigger__time_pattern:
      name: "Time Pattern Trigger"
      description: "You can use any trigger here but you should use a time_pattern trigger."
      selector:
        trigger:

mode: single

trigger_variables: {}

triggers:
  # Time Trigger
  !input trigger__time_pattern

variables:
  input_smoke_detector_devices: !input 'smoke_detector_devices'
  detector__heartbeat_switch: >-
    {% set data = namespace(heartbeat_entities=[]) %}
    {% for device in input_smoke_detector_devices %}
      {% set heartbeat_entity = device_entities(device) | select('match', 'switch.*_heartbeat_indicator$') | list %}
      {% set data.heartbeat_entities = data.heartbeat_entities + heartbeat_entity %}
    {% endfor %}
    {{ data.heartbeat_entities }}

actions:
  - alias: "Toggle switch"
    action: switch.toggle
    target:
      entity_id: "{{ detector__heartbeat_switch }}"
  - alias: "Forced delay"
    delay:
      seconds: 15
  - alias: "Toggle switch"
    action: switch.toggle
    target:
      entity_id: "{{ detector__heartbeat_switch }}"

